# AetherCore project file.

[app]
startupscene = "Menu"
targetfps = 0

[graphics]
asynccompute = true
fxaa = false
vsync = false

[paths]
assets = "assets"
prefabs = "assets/prefabs"
scenes = "scenes"
scripts = "scripts"

[project]
name = "INKBOUND"
version = 1
