# AetherCore tile set

[tile]
0.animation_fps = 8.00
0.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
0.collision = "full"
0.frame_count = 0.00
0.id = "b3a0f397b4eb9d2e"
0.name = "Sprite_0_0"
0.property_count = 0.00
0.sprite_id = "18b0c944dba61927"
1.animation_fps = 8.00
1.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
1.collision = "full"
1.frame_count = 0.00
1.id = "ade4ff9ebbb0513e"
1.name = "Sprite_0_1"
1.property_count = 0.00
1.sprite_id = "18b0c844dba61774"
10.animation_fps = 8.00
10.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
10.collision = "full"
10.frame_count = 0.00
10.id = "26c5478279cf1e3b"
10.name = "Sprite_1_1"
10.property_count = 0.00
10.sprite_id = "0f8c9744d655874b"
11.animation_fps = 8.00
11.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
11.collision = "full"
11.frame_count = 0.00
11.id = "74518c9d80cae6f3"
11.name = "Sprite_1_2"
11.property_count = 0.00
11.sprite_id = "0f8c9844d65588fe"
12.animation_fps = 8.00
12.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
12.collision = "full"
12.frame_count = 0.00
12.id = "dbcb6d961d695aa4"
12.name = "Sprite_1_3"
12.property_count = 0.00
12.sprite_id = "0f8c9944d6558ab1"
13.animation_fps = 8.00
13.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
13.collision = "full"
13.frame_count = 0.00
13.id = "4b2323994a25206e"
13.name = "Sprite_1_4"
13.property_count = 0.00
13.sprite_id = "0f8c9a44d6558c64"
14.animation_fps = 8.00
14.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
14.collision = "full"
14.frame_count = 0.00
14.id = "a1a0cbf7fdd222ea"
14.name = "Sprite_1_5"
14.property_count = 0.00
14.sprite_id = "0f8c9b44d6558e17"
15.animation_fps = 8.00
15.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
15.collision = "full"
15.frame_count = 0.00
15.id = "4aca4c422e9ca081"
15.name = "Sprite_1_6"
15.property_count = 0.00
15.sprite_id = "0f8c9c44d6558fca"
16.animation_fps = 8.00
16.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
16.collision = "full"
16.frame_count = 0.00
16.id = "a3838a84551a8e28"
16.name = "Sprite_1_7"
16.property_count = 0.00
16.sprite_id = "0f8c9d44d655917d"
17.animation_fps = 8.00
17.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
17.collision = "full"
17.frame_count = 0.00
17.id = "bac3e12a95098a9d"
17.name = "Sprite_1_8"
17.property_count = 0.00
17.sprite_id = "0f8c8e44d6557800"
18.animation_fps = 8.00
18.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
18.collision = "full"
18.frame_count = 0.00
18.id = "558951884d52552e"
18.name = "Sprite_2_0"
18.property_count = 0.00
18.sprite_id = "06acfb44d13fc11d"
19.animation_fps = 8.00
19.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
19.collision = "full"
19.frame_count = 0.00
19.id = "e612714a678c9d7e"
19.name = "Sprite_2_1"
19.property_count = 0.00
19.sprite_id = "06acfa44d13fbf6a"
2.animation_fps = 8.00
2.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
2.collision = "full"
2.frame_count = 0.00
2.id = "8f51f650b688b918"
2.name = "Sprite_0_2"
2.property_count = 0.00
2.sprite_id = "18b0cb44dba61c8d"
20.animation_fps = 8.00
20.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
20.collision = "full"
20.frame_count = 0.00
20.id = "18addf9902414f8b"
20.name = "Sprite_2_2"
20.property_count = 0.00
20.sprite_id = "06acf944d13fbdb7"
21.animation_fps = 8.00
21.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
21.collision = "full"
21.frame_count = 0.00
21.id = "f97bc0b735cf6a0b"
21.name = "Sprite_2_3"
21.property_count = 0.00
21.sprite_id = "06acf844d13fbc04"
22.animation_fps = 8.00
22.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
22.collision = "full"
22.frame_count = 0.00
22.id = "2e5e87b6c036b601"
22.name = "Sprite_2_4"
22.property_count = 0.00
22.sprite_id = "06acf744d13fba51"
23.animation_fps = 8.00
23.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
23.collision = "full"
23.frame_count = 0.00
23.id = "afa2724b808f428a"
23.name = "Sprite_2_5"
23.property_count = 0.00
23.sprite_id = "06acf644d13fb89e"
24.animation_fps = 8.00
24.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
24.collision = "full"
24.frame_count = 0.00
24.id = "6d2041620ec9b169"
24.name = "Sprite_2_6"
24.property_count = 0.00
24.sprite_id = "06acf544d13fb6eb"
25.animation_fps = 8.00
25.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
25.collision = "full"
25.frame_count = 0.00
25.id = "07fe7ab157573588"
25.name = "Sprite_2_7"
25.property_count = 0.00
25.sprite_id = "06acf444d13fb538"
26.animation_fps = 8.00
26.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
26.collision = "full"
26.frame_count = 0.00
26.id = "0eaf844874f33778"
26.name = "Sprite_2_8"
26.property_count = 0.00
26.sprite_id = "06acf344d13fb385"
27.animation_fps = 8.00
27.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
27.collision = "rect"
27.one_way = "up"
27.collision_x = 0.00
27.collision_y = 0.625
27.collision_w = 1.00
27.collision_h = 0.375
27.frame_count = 0.00
27.id = "97c2225b18cf26da"
27.name = "Sprite_3_0"
27.property_count = 0.00
27.sprite_id = "fda43844cc06b396"
28.animation_fps = 8.00
28.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
28.collision = "rect"
28.one_way = "up"
28.collision_x = 0.00
28.collision_y = 0.625
28.collision_w = 1.00
28.collision_h = 0.375
28.frame_count = 0.00
28.id = "38ca096a8e2905ca"
28.name = "Sprite_3_1"
28.property_count = 0.00
28.sprite_id = "fda43944cc06b549"
29.animation_fps = 8.00
29.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
29.collision = "rect"
29.one_way = "up"
29.collision_x = 0.00
29.collision_y = 0.625
29.collision_w = 1.00
29.collision_h = 0.375
29.frame_count = 0.00
29.id = "9dcc6d8b6c445c0d"
29.name = "Sprite_3_2"
29.property_count = 0.00
29.sprite_id = "fda43644cc06b030"
3.animation_fps = 8.00
3.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
3.collision = "full"
3.frame_count = 0.00
3.id = "ff818391404e982b"
3.name = "Sprite_0_3"
3.property_count = 0.00
3.sprite_id = "18b0ca44dba61ada"
30.animation_fps = 8.00
30.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
30.collision = "full"
30.frame_count = 0.00
30.id = "f991e49bffc93d1f"
30.name = "Sprite_3_3"
30.property_count = 0.00
30.sprite_id = "fda43744cc06b1e3"
31.animation_fps = 8.00
31.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
31.collision = "full"
31.frame_count = 0.00
31.id = "f7ced4e864fe5f8a"
31.name = "Sprite_3_4"
31.property_count = 0.00
31.sprite_id = "fda43c44cc06ba62"
32.animation_fps = 8.00
32.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
32.collision = "full"
32.frame_count = 0.00
32.id = "1ff19c49e8b24abe"
32.name = "Sprite_3_5"
32.property_count = 0.00
32.sprite_id = "fda43d44cc06bc15"
33.animation_fps = 8.00
33.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
33.collision = "full"
33.frame_count = 0.00
33.id = "31e352fca2811b80"
33.name = "Sprite_3_6"
33.property_count = 0.00
33.sprite_id = "fda43a44cc06b6fc"
34.animation_fps = 8.00
34.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
34.collision = "full"
34.frame_count = 0.00
34.id = "826950d18a9ed95a"
34.name = "Sprite_3_7"
34.property_count = 0.00
34.sprite_id = "fda43b44cc06b8af"
35.animation_fps = 8.00
35.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
35.collision = "full"
35.frame_count = 0.00
35.id = "2e7c135c0a49a684"
35.name = "Sprite_3_8"
35.property_count = 0.00
35.sprite_id = "fda44044cc06c12e"
4.animation_fps = 8.00
4.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
4.collision = "full"
4.frame_count = 0.00
4.id = "3a3728da0fe2ae79"
4.name = "Sprite_0_4"
4.property_count = 0.00
4.sprite_id = "18b0c544dba6125b"
5.animation_fps = 8.00
5.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
5.collision = "full"
5.frame_count = 0.00
5.id = "99b2bc6a516ea187"
5.name = "Sprite_0_5"
5.property_count = 0.00
5.sprite_id = "18b0c444dba610a8"
6.animation_fps = 8.00
6.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
6.collision = "full"
6.frame_count = 0.00
6.id = "28ee0364b884cc8b"
6.name = "Sprite_0_6"
6.property_count = 0.00
6.sprite_id = "18b0c744dba615c1"
7.animation_fps = 8.00
7.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
7.collision = "full"
7.frame_count = 0.00
7.id = "e9903ba87c545355"
7.name = "Sprite_0_7"
7.property_count = 0.00
7.sprite_id = "18b0c644dba6140e"
8.animation_fps = 8.00
8.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
8.collision = "full"
8.frame_count = 0.00
8.id = "b7c3aa75f1f147b5"
8.name = "Sprite_0_8"
8.property_count = 0.00
8.sprite_id = "18b0c144dba60b8f"
9.animation_fps = 8.00
9.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
9.collision = "full"
9.frame_count = 0.00
9.id = "080e8ea0580d629e"
9.name = "Sprite_1_0"
9.property_count = 0.00
9.sprite_id = "0f8c9644d6558598"

[tileset]
cell_size = 1.00
name = "sandbox"
schema_version = 1.00
tile_count = 36.00
