# AetherCore sprite atlas

[atlas]
filter = "nearest"
import_preset = "grid"
import_provenance = "native"
pixels_per_unit = 16.00
schema_version = 2.00
sprite_count = 8.00
texture = "project://assets/textures/player/idle32x32.png"
texture_height = 128.00
texture_width = 64.00
wrap = "clamp"

[slice]
alpha_threshold = 1.00
cell_height = 32.00
cell_width = 32.00
columns = 0.00
origin = "top-left"
padding_x = 0.00
padding_y = 0.00
rows = 0.00
spacing_x = 0.00
spacing_y = 0.00
trim_alpha = false

[sprite]
0.border_bottom = 0.00
0.border_left = 0.00
0.border_right = 0.00
0.border_top = 0.00
0.collision_count = 0.00
0.height = 32.00
0.id = "d8ab56e0b06ece94"
0.name = "Sprite_0_0"
0.persistent_key = "grid:0:0"
0.pivot_x = 0.50
0.pivot_y = 0.50
0.width = 32.00
0.x = 0.00
0.y = 0.00
1.border_bottom = 0.00
1.border_left = 0.00
1.border_right = 0.00
1.border_top = 0.00
1.collision_count = 0.00
1.height = 32.00
1.id = "d8ab57e0b06ed047"
1.name = "Sprite_0_1"
1.persistent_key = "grid:0:1"
1.pivot_x = 0.50
1.pivot_y = 0.50
1.width = 32.00
1.x = 32.00
1.y = 0.00
2.border_bottom = 0.00
2.border_left = 0.00
2.border_right = 0.00
2.border_top = 0.00
2.collision_count = 0.00
2.height = 32.00
2.id = "e198e9e0b590c2d3"
2.name = "Sprite_1_0"
2.persistent_key = "grid:1:0"
2.pivot_x = 0.50
2.pivot_y = 0.50
2.width = 32.00
2.x = 0.00
2.y = 32.00
3.border_bottom = 0.00
3.border_left = 0.00
3.border_right = 0.00
3.border_top = 0.00
3.collision_count = 0.00
3.height = 32.00
3.id = "e198e8e0b590c120"
3.name = "Sprite_1_1"
3.persistent_key = "grid:1:1"
3.pivot_x = 0.50
3.pivot_y = 0.50
3.width = 32.00
3.x = 32.00
3.y = 32.00
4.border_bottom = 0.00
4.border_left = 0.00
4.border_right = 0.00
4.border_top = 0.00
4.collision_count = 0.00
4.height = 32.00
4.id = "c68c78e0a5f193a2"
4.name = "Sprite_2_0"
4.persistent_key = "grid:2:0"
4.pivot_x = 0.50
4.pivot_y = 0.50
4.width = 32.00
4.x = 0.00
4.y = 64.00
5.border_bottom = 0.00
5.border_left = 0.00
5.border_right = 0.00
5.border_top = 0.00
5.collision_count = 0.00
5.height = 32.00
5.id = "c68c79e0a5f19555"
5.name = "Sprite_2_1"
5.persistent_key = "grid:2:1"
5.pivot_x = 0.50
5.pivot_y = 0.50
5.width = 32.00
5.x = 32.00
5.y = 64.00
6.border_bottom = 0.00
6.border_left = 0.00
6.border_right = 0.00
6.border_top = 0.00
6.collision_count = 0.00
6.height = 32.00
6.id = "cf951be0ab2a6ac9"
6.name = "Sprite_3_0"
6.persistent_key = "grid:3:0"
6.pivot_x = 0.50
6.pivot_y = 0.50
6.width = 32.00
6.x = 0.00
6.y = 96.00
7.border_bottom = 0.00
7.border_left = 0.00
7.border_right = 0.00
7.border_top = 0.00
7.collision_count = 0.00
7.height = 32.00
7.id = "cf951ae0ab2a6916"
7.name = "Sprite_3_1"
7.persistent_key = "grid:3:1"
7.pivot_x = 0.50
7.pivot_y = 0.50
7.width = 32.00
7.x = 32.00
7.y = 96.00
