[scene]
name = "Untitled"
version = 6

[[entities]]
name = "Platform"
parent = -1
position = [0.0, 0.0, 0.0]
euler = [0.0, 0.0, 0.0]
scale = [1.0, 1.0, 1.0]
[entities.mesh]
kind = "primitive"
path = "cube"
index = 0
[entities.physics]
shape = "box"
motion = "static"
half_extents = [5.0, 0.5, 5.0]
radius = 0.5
half_height = 0.5

[[entities]]
name = "Cube"
parent = -1
position = [0.0, 4.0, 0.0]
euler = [0.0, 0.0, 0.0]
scale = [1.0, 1.0, 1.0]
[entities.mesh]
kind = "primitive"
path = "cube"
index = 0
[entities.physics]
shape = "box"
motion = "dynamic"
half_extents = [0.5, 0.5, 0.5]
radius = 0.5
half_height = 0.5
