#include "MaterialImporter.hpp"

#include <algorithm>
#include <cctype>
#include <fstream>
#include <iostream>
#include <set>
#include <sstream>

// ---------------------------------------------------------------------------
// Public
// ---------------------------------------------------------------------------

int MaterialImporter::ImportDirectory(const fs::path& sourceDir)
{
	if (!fs::is_directory(sourceDir))
	{
		std::cerr << "AssetPacker: source directory not found: " << sourceDir << "\n";
		return -1;
	}

	int written = 0;
	for (const auto& entry: fs::recursive_directory_iterator(sourceDir))
	{
		if (!entry.is_directory())
		{
			continue;
		}
		if (GeneratePropertiesForFolder(entry.path()))
		{
			++written;
		}
	}

	std::cout << "AssetPacker: wrote " << written << " properties.toml file(s)\n";
	return written;
}

// ---------------------------------------------------------------------------
// Private - file-write helpers
// ---------------------------------------------------------------------------

bool MaterialImporter::ShouldWrite(const fs::path& outPath)
{
	if (!fs::exists(outPath))
	{
		return true;
	}

	std::ifstream in(outPath);
	if (!in)
	{
		return false;
	}

	// Read first non-empty line to check for auto-generated marker or placeholder.
	std::string line;
	while (std::getline(in, line))
	{
		if (line.empty()) continue;
		if (line.find("# Auto-generated by AssetPacker --import-materials") != std::string::npos)
			return true;
		if (line.find("albedo = \"albedo\"") != std::string::npos ||
		    line.find("normal = \"normal\"") != std::string::npos ||
		    line.find("metallicRoughness = \"roughness\"") != std::string::npos)
			return true;
		return false;
	}
	return false;
}

bool MaterialImporter::GeneratePropertiesForFolder(const fs::path& folder)
{
	if (!fs::is_directory(folder))
	{
		return false;
	}

	const fs::path outPath = folder / "properties.toml";
	if (!ShouldWrite(outPath))
	{
		return false;
	}

	std::vector<TextureFile> textureFiles;
	textureFiles.reserve(16);
	for (const auto& entry: fs::directory_iterator(folder))
	{
		if (!entry.is_regular_file() || !IsImageExtension(entry.path()))
		{
			continue;
		}

		TextureFile file;
		file.filename = entry.path().filename().generic_string();
		file.stem = ToLowerAscii(entry.path().stem().string());
		file.normalizedStem = NormalizeForMatch(file.stem);
		file.tokens = TokenizeStem(file.stem);
		textureFiles.push_back(std::move(file));
	}

	if (textureFiles.empty())
	{
		return false;
	}

	const auto albedo = FindBestTexture(textureFiles, { "albedo", "basecolor", "base_color", "diffuse", "color", "col" }, {}, { "normal", "roughness", "metallic", "occlusion", "ao", "emissive", "opacity", "alpha", "displacement", "height" });
	const auto normal = FindBestTexture(textureFiles, { "normal", "nrm", "nor" }, { "normalgl", "opengl" }, { "normaldx", "directx" });
	const auto metalRough = FindBestTexture(textureFiles, { "metallicroughness", "metalrough", "metal_rough", "orm", "rma", "arm", "mra" });
	const auto roughness = FindBestTexture(textureFiles, { "roughness", "rough" });
	const auto metallic = FindBestTexture(textureFiles, { "metallic", "metalness", "metal" });
	const auto occlusion = FindBestTexture(textureFiles, { "occlusion", "ao", "ambientocclusion" });
	const auto emissive = FindBestTexture(textureFiles, { "emissive", "emission", "emit" });

	if (!albedo && !normal && !metalRough && !roughness && !metallic && !occlusion && !emissive)
	{
		return false;
	}

	// Build content in-memory so we can compare against the existing file before
	// overwriting - avoids changing the mtime when nothing has changed, which
	// keeps the incremental-build cache intact.
	std::ostringstream ss;
	ss << "# Auto-generated by AssetPacker --import-materials\n\n";
	ss << "[material]\n";
	ss << "baseColorFactor = [1.0, 1.0, 1.0, 1.0]\n";
	ss << "metallicFactor = 0.0\n";
	ss << "roughnessFactor = 1.0\n";
	ss << "occlusionStrength = 1.0\n";
	ss << "doubleSided = false\n\n";
	ss << "[textures]\n";
	if (albedo)
		ss << "albedo = \"" << *albedo << "\"\n";
	if (normal)
		ss << "normal = \"" << *normal << "\"\n";
	if (metalRough)
	{
		ss << "metallicRoughness = \"" << *metalRough << "\"\n";
	}
	else if (roughness)
	{
		// No combined ORM map found - promote the roughness-only map to the
		// metallicRoughness slot and zero out metallic via the scalar factor so
		// the shader doesn't read junk from the blue channel.
		ss << "metallicRoughness = \"" << *roughness << "\"\n";
	}
	else if (metallic)
	{
		// Metallic-only map: promote and zero roughness via scalar factor.
		ss << "metallicRoughness = \"" << *metallic << "\"\n";
	}
	if (occlusion)
		ss << "occlusion = \"" << *occlusion << "\"\n";
	if (emissive)
		ss << "emissive = \"" << *emissive << "\"\n";

	const std::string newContent = ss.str();

	// Compare with existing file content - only write if different to preserve mtime.
	if (fs::exists(outPath))
	{
		std::ifstream in(outPath);
		if (in)
		{
			const std::string existing((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());
			if (existing == newContent)
				return false;
		}
	}

	std::ofstream out(outPath, std::ios::trunc);
	if (!out)
	{
		std::cerr << "  WARNING: failed to write '" << outPath.generic_string() << "'\n";
		return false;
	}

	out << newContent;
	if (!out)
	{
		std::cerr << "  WARNING: write error on '" << outPath.generic_string() << "'\n";
		return false;
	}

	std::cout << "  + wrote " << outPath.generic_string() << "\n";
	return true;
}

// ---------------------------------------------------------------------------
// Private - string / texture-matching helpers
// ---------------------------------------------------------------------------

std::string MaterialImporter::ToLowerAscii(std::string s)
{
	std::transform(s.begin(), s.end(), s.begin(), [](const unsigned char c) { return static_cast<char>(std::tolower(c)); });
	return s;
}

std::string MaterialImporter::NormalizeForMatch(std::string s)
{
	s = ToLowerAscii(std::move(s));
	s.erase(std::remove_if(s.begin(), s.end(), [](const unsigned char c) { return !std::isalnum(c); }), s.end());
	return s;
}

std::vector<std::string> MaterialImporter::TokenizeStem(const std::string& stem)
{
	std::vector<std::string> tokens;
	std::string current;
	current.reserve(stem.size());

	for (const unsigned char c: stem)
	{
		if (std::isalnum(c))
		{
			current.push_back(static_cast<char>(std::tolower(c)));
			continue;
		}

		if (!current.empty())
		{
			tokens.push_back(std::move(current));
			current.clear();
		}
	}

	if (!current.empty())
	{
		tokens.push_back(std::move(current));
	}

	return tokens;
}

bool MaterialImporter::IsImageExtension(const fs::path& path)
{
	const std::string ext = ToLowerAscii(path.extension().string());
	static const std::set<std::string> kImageExts = { ".png", ".jpg", ".jpeg", ".tga", ".bmp", ".webp", ".dds", ".ktx2" };
	return kImageExts.contains(ext);
}

bool MaterialImporter::ContainsAlias(const TextureFile& file, std::string_view alias)
{
	const std::string normalizedAlias = NormalizeForMatch(std::string(alias));
	if (normalizedAlias.empty())
	{
		return false;
	}

	if (normalizedAlias.size() <= 3)
	{
		return std::find(file.tokens.begin(), file.tokens.end(), normalizedAlias) != file.tokens.end();
	}

	if (file.normalizedStem.find(normalizedAlias) != std::string::npos)
	{
		return true;
	}

	return std::find(file.tokens.begin(), file.tokens.end(), normalizedAlias) != file.tokens.end();
}

namespace
{
	constexpr int kIncludeAliasScore   = 25;
	constexpr int kExactStemBonus      = 50;
	constexpr int kPreferredAliasScore = 20;
}

std::optional<std::string> MaterialImporter::FindBestTexture(const std::vector<TextureFile>& files, std::initializer_list<std::string_view> includeAliases, std::initializer_list<std::string_view> preferredAliases, std::initializer_list<std::string_view> excludeAliases)
{
	std::optional<std::string> best;
	int bestScore = 0;

	for (const TextureFile& file: files)
	{
		bool excluded = false;
		for (const std::string_view alias: excludeAliases)
		{
			if (ContainsAlias(file, alias))
			{
				excluded = true;
				break;
			}
		}
		if (excluded)
		{
			continue;
		}

		int score = 0;
		for (const std::string_view alias: includeAliases)
		{
			if (!ContainsAlias(file, alias))
			{
				continue;
			}

			score += kIncludeAliasScore;
			if (file.normalizedStem == NormalizeForMatch(std::string(alias)))
			{
				score += kExactStemBonus;
			}
		}

		for (const std::string_view alias: preferredAliases)
		{
			if (ContainsAlias(file, alias))
			{
				score += kPreferredAliasScore;
			}
		}

		if (score <= 0)
		{
			continue;
		}

		if (score > bestScore || !best.has_value() || (score == bestScore && file.filename < *best))
		{
			bestScore = score;
			best = file.filename;
		}
	}

	return best;
}
