#pragma once

#include <filesystem>
#include <vector>

namespace MaterialProcessor
{
	// Parse a properties.toml file (generated by MaterialImporter) and produce a
	// binary .material file using MaterialHeaderDisk.
	//
	// sourcePath is the on-disk path to the .toml file.
	// sourceDir is the root source directory (used to locate companion files).
	//
	// Returns empty if parsing fails.
	[[nodiscard]] std::vector<std::byte> Process(
	    const std::vector<std::byte>& tomlData,
	    const std::filesystem::path&  sourcePath,
	    const std::filesystem::path&  sourceDir);
} // namespace MaterialProcessor
