#pragma once

#include <cstddef>
#include <filesystem>
#include <span>

#include "PipelineUtils.hpp"

namespace MaterialProcessor
{
	// Parse a properties.toml file (generated by MaterialImporter) and produce a
	// binary .material file using MaterialHeaderDisk.
	//
	// sourcePath is the on-disk path to the .toml file.
	// sourceDir is the root source directory (used to locate companion files).
	//
	// Returns empty if parsing fails.
	[[nodiscard]] ByteBuffer Process(std::span<const std::byte> tomlData, const std::filesystem::path& sourcePath, const std::filesystem::path& sourceDir);
} // namespace MaterialProcessor
