# AetherCore tile set

[tile]
0.animation_fps = 8.00
0.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
0.collision = "full"
0.frame_count = 0.00
0.id = "c619030a69293a76"
0.name = "Sprite_0_0"
0.property_count = 0.00
0.sprite_id = "18b0c944dba61927"
1.animation_fps = 8.00
1.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
1.collision = "full"
1.frame_count = 0.00
1.id = "f75e0ccc6cf7c2d6"
1.name = "Sprite_0_1"
1.property_count = 0.00
1.sprite_id = "18b0c844dba61774"
10.animation_fps = 8.00
10.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
10.collision = "full"
10.frame_count = 0.00
10.id = "ea5f86fa3f7f4e43"
10.name = "Sprite_1_1"
10.property_count = 0.00
10.sprite_id = "0f8c9744d655874b"
11.animation_fps = 8.00
11.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
11.collision = "full"
11.frame_count = 0.00
11.id = "107d4a2c71edd9db"
11.name = "Sprite_1_2"
11.property_count = 0.00
11.sprite_id = "0f8c9844d65588fe"
12.animation_fps = 8.00
12.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
12.collision = "full"
12.frame_count = 0.00
12.id = "a8f213ed40ab903c"
12.name = "Sprite_1_3"
12.property_count = 0.00
12.sprite_id = "0f8c9944d6558ab1"
13.animation_fps = 8.00
13.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
13.collision = "full"
13.frame_count = 0.00
13.id = "620b8777fa636c36"
13.name = "Sprite_1_4"
13.property_count = 0.00
13.sprite_id = "0f8c9a44d6558c64"
14.animation_fps = 8.00
14.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
14.collision = "full"
14.frame_count = 0.00
14.id = "76a703a456ef8d52"
14.name = "Sprite_1_5"
14.property_count = 0.00
14.sprite_id = "0f8c9b44d6558e17"
15.animation_fps = 8.00
15.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
15.collision = "full"
15.frame_count = 0.00
15.id = "325f20ab5e3bea09"
15.name = "Sprite_1_6"
15.property_count = 0.00
15.sprite_id = "0f8c9c44d6558fca"
16.animation_fps = 8.00
16.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
16.collision = "full"
16.frame_count = 0.00
16.id = "1eeebb9aab6d9fd0"
16.name = "Sprite_1_7"
16.property_count = 0.00
16.sprite_id = "0f8c9d44d655917d"
17.animation_fps = 8.00
17.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
17.collision = "full"
17.frame_count = 0.00
17.id = "aeb11e97f29a9455"
17.name = "Sprite_1_8"
17.property_count = 0.00
17.sprite_id = "0f8c8e44d6557800"
18.animation_fps = 8.00
18.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
18.collision = "full"
18.frame_count = 0.00
18.id = "e916b60476237bc6"
18.name = "Sprite_2_0"
18.property_count = 0.00
18.sprite_id = "06acfb44d13fc11d"
19.animation_fps = 8.00
19.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
19.collision = "full"
19.frame_count = 0.00
19.id = "6c712336e89f9e76"
19.name = "Sprite_2_1"
19.property_count = 0.00
19.sprite_id = "06acfa44d13fbf6a"
2.animation_fps = 8.00
2.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
2.collision = "full"
2.frame_count = 0.00
2.id = "11207542aa1428d0"
2.name = "Sprite_0_2"
2.property_count = 0.00
2.sprite_id = "18b0cb44dba61c8d"
20.animation_fps = 8.00
20.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
20.collision = "full"
20.frame_count = 0.00
20.id = "b104a00bbc961733"
20.name = "Sprite_2_2"
20.property_count = 0.00
20.sprite_id = "06acf944d13fbdb7"
21.animation_fps = 8.00
21.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
21.collision = "full"
21.frame_count = 0.00
21.id = "f45981bda25a6953"
21.name = "Sprite_2_3"
21.property_count = 0.00
21.sprite_id = "06acf844d13fbc04"
22.animation_fps = 8.00
22.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
22.collision = "full"
22.frame_count = 0.00
22.id = "6a672f78bc76dfd9"
22.name = "Sprite_2_4"
22.property_count = 0.00
22.sprite_id = "06acf744d13fba51"
23.animation_fps = 8.00
23.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
23.collision = "full"
23.frame_count = 0.00
23.id = "c7f86f89acfd2d82"
23.name = "Sprite_2_5"
23.property_count = 0.00
23.sprite_id = "06acf644d13fb89e"
24.animation_fps = 8.00
24.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
24.collision = "full"
24.frame_count = 0.00
24.id = "12052e2bd2fb1e21"
24.name = "Sprite_2_6"
24.property_count = 0.00
24.sprite_id = "06acf544d13fb6eb"
25.animation_fps = 8.00
25.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
25.collision = "full"
25.frame_count = 0.00
25.id = "6d3ce414dc028fb0"
25.name = "Sprite_2_7"
25.property_count = 0.00
25.sprite_id = "06acf444d13fb538"
26.animation_fps = 8.00
26.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
26.collision = "full"
26.frame_count = 0.00
26.id = "e8633ed2fb5596b0"
26.name = "Sprite_2_8"
26.property_count = 0.00
26.sprite_id = "06acf344d13fb385"
27.animation_fps = 8.00
27.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
27.collision = "full"
27.frame_count = 0.00
27.id = "ceeace3b87041072"
27.name = "Sprite_3_0"
27.property_count = 0.00
27.sprite_id = "fda43844cc06b396"
28.animation_fps = 8.00
28.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
28.collision = "full"
28.frame_count = 0.00
28.id = "aaa2d81544d375c2"
28.name = "Sprite_3_1"
28.property_count = 0.00
28.sprite_id = "fda43944cc06b549"
29.animation_fps = 8.00
29.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
29.collision = "full"
29.frame_count = 0.00
29.id = "26a317c46f115305"
29.name = "Sprite_3_2"
29.property_count = 0.00
29.sprite_id = "fda43644cc06b030"
3.animation_fps = 8.00
3.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
3.collision = "full"
3.frame_count = 0.00
3.id = "22c50cb8ea095dd3"
3.name = "Sprite_0_3"
3.property_count = 0.00
3.sprite_id = "18b0ca44dba61ada"
30.animation_fps = 8.00
30.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
30.collision = "full"
30.frame_count = 0.00
30.id = "12d89389ef46dff7"
30.name = "Sprite_3_3"
30.property_count = 0.00
30.sprite_id = "fda43744cc06b1e3"
31.animation_fps = 8.00
31.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
31.collision = "full"
31.frame_count = 0.00
31.id = "ed5d1b750ca1b502"
31.name = "Sprite_3_4"
31.property_count = 0.00
31.sprite_id = "fda43c44cc06ba62"
32.animation_fps = 8.00
32.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
32.collision = "full"
32.frame_count = 0.00
32.id = "ed3b1ef1dcae5076"
32.name = "Sprite_3_5"
32.property_count = 0.00
32.sprite_id = "fda43d44cc06bc15"
33.animation_fps = 8.00
33.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
33.collision = "full"
33.frame_count = 0.00
33.id = "0f7ee511d65c8278"
33.name = "Sprite_3_6"
33.property_count = 0.00
33.sprite_id = "fda43a44cc06b6fc"
34.animation_fps = 8.00
34.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
34.collision = "full"
34.frame_count = 0.00
34.id = "a2e07ab7e2bda762"
34.name = "Sprite_3_7"
34.property_count = 0.00
34.sprite_id = "fda43b44cc06b8af"
35.animation_fps = 8.00
35.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
35.collision = "full"
35.frame_count = 0.00
35.id = "44530d77b4b2582c"
35.name = "Sprite_3_8"
35.property_count = 0.00
35.sprite_id = "fda44044cc06c12e"
36.animation_fps = 8.00
36.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
36.collision = "full"
36.frame_count = 0.00
36.id = "381a3baccb234c31"
36.name = "Sprite_4_0"
36.property_count = 0.00
36.sprite_id = "e543aa37b98e8a75"
37.animation_fps = 8.00
37.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
37.collision = "full"
37.frame_count = 0.00
37.id = "0391ea7ad806cb3c"
37.name = "Sprite_4_1"
37.one_way = "up"
37.property_count = 0.00
37.sprite_id = "cbea9596a020529a"
38.animation_fps = 8.00
38.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
38.collision = "full"
38.frame_count = 0.00
38.id = "2875dbb59102c737"
38.name = "Sprite_4_2"
38.property_count = 0.00
38.sprite_id = "2611534f10de2f31"
39.animation_fps = 8.00
39.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
39.collision = "full"
39.frame_count = 0.00
39.id = "53ab617c23e3032d"
39.name = "Sprite_4_3"
39.property_count = 0.00
39.sprite_id = "7986d957c1f3949e"
4.animation_fps = 8.00
4.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
4.collision = "full"
4.frame_count = 0.00
4.id = "e2b1d9cfcf083681"
4.name = "Sprite_0_4"
4.property_count = 0.00
4.sprite_id = "18b0c544dba6125b"
40.animation_fps = 8.00
40.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
40.collision = "full"
40.frame_count = 0.00
40.id = "f2b03bf60358fe68"
40.name = "Sprite_4_4"
40.property_count = 0.00
40.sprite_id = "d098bb5dc85b781a"
41.animation_fps = 8.00
41.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
41.collision = "full"
41.frame_count = 0.00
41.id = "f77e22e37545fad7"
41.name = "Sprite_4_5"
41.property_count = 0.00
41.sprite_id = "1855cd2b76b83edb"
42.animation_fps = 8.00
42.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
42.collision = "full"
42.frame_count = 0.00
42.id = "769cc1bdbddc436b"
42.name = "Sprite_4_6"
42.property_count = 0.00
42.sprite_id = "432ef9314961d30d"
43.animation_fps = 8.00
43.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
43.collision = "full"
43.frame_count = 0.00
43.id = "23e2fc50e15b3bb5"
43.name = "Sprite_4_7"
43.property_count = 0.00
43.sprite_id = "3940e26eb12672d9"
44.animation_fps = 8.00
44.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
44.collision = "full"
44.frame_count = 0.00
44.id = "ae9d9980fdef60ca"
44.name = "Sprite_4_8"
44.property_count = 0.00
44.sprite_id = "e0141f36a9ffa657"
5.animation_fps = 8.00
5.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
5.collision = "full"
5.frame_count = 0.00
5.id = "45361f18ffcb06ff"
5.name = "Sprite_0_5"
5.property_count = 0.00
5.sprite_id = "18b0c444dba610a8"
6.animation_fps = 8.00
6.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
6.collision = "full"
6.frame_count = 0.00
6.id = "6eb18e36d5a6f713"
6.name = "Sprite_0_6"
6.property_count = 0.00
6.sprite_id = "18b0c744dba615c1"
7.animation_fps = 8.00
7.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
7.collision = "full"
7.frame_count = 0.00
7.id = "4c7161acbeb4b81d"
7.name = "Sprite_0_7"
7.property_count = 0.00
7.sprite_id = "18b0c644dba6140e"
8.animation_fps = 8.00
8.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
8.collision = "full"
8.frame_count = 0.00
8.id = "716b27439605799d"
8.name = "Sprite_0_8"
8.property_count = 0.00
8.sprite_id = "18b0c144dba60b8f"
9.animation_fps = 8.00
9.atlas = "project://assets/textures/world/tileset_16x16.spriteatlas.toml"
9.collision = "full"
9.frame_count = 0.00
9.id = "8f1de5738ac0f446"
9.name = "Sprite_1_0"
9.property_count = 0.00
9.sprite_id = "0f8c9644d6558598"

[tileset]
cell_size = 1.00
name = "arena"
schema_version = 1.00
tile_count = 45.00
