# AetherCore sprite animation

[animation]
atlas = "project://assets/textures/player/walk32x32.spriteatlas.toml"
event_count = 0.00
frame_count = 1.00
loop_mode = "hold"
name = "player_jump"
schema_version = 1.00

[frame]
0.duration = 0.50
0.sprite_id = "1984ce2a282d0c4a"
