# AetherCore project file.

[app]
startupscene = "Workbench"

[editor]
flavor = "twinsanity"

[graphics]
asynccompute = true
autoexposure = false
bloomstrength = 0.00
fxaa = false
gtao = false
tonemap = "Linear"
vsync = true

[paths]
assets = "assets"
prefabs = "assets/prefabs"
scenes = "scenes"
scripts = "scripts"

[project]
name = "Twinsanity"
version = 1

[publish]
buildscripts = true
cleanoutput = true
openafter = true
outputroot = "D:\\AetherCore\\projects\\Twinsanity\\Builds"
platformname = "Windows"
productname = "Twinsanity"
synceditorpak = true
usepackagetemplate = true
verifyoutput = true

[window]
height = 1440
width = 2560
