# AetherCore project file.

[app]
startupscene = "Testing"
targetfps = 0

[graphics]
asynccompute = true
fxaa = false
vsync = true

[paths]
assets = "assets"
prefabs = "assets/prefabs"
scenes = "scenes"
scripts = "scripts"

[project]
name = "Testing Project"
version = 1

[publish]
buildscripts = true
cleanoutput = true
openafter = true
outputroot = "D:\\AetherCore\\projects\\TestingProject\\Builds"
platformname = "Windows"
productname = "TestingProject"
synceditorpak = true
usepackagetemplate = true
verifyoutput = true

[window]
height = 1440
width = 2560
