# AetherCore project file.

[project]
version = 1
name = "Testing Project"

[paths]
assets  = "assets"
scenes  = "scenes"
prefabs = "assets/prefabs"
scripts = "scripts"

[app]
startupScene = "Testing"
targetFps = 0

[window]
width = 1920
height = 1080

[graphics]
vsync = false
fxaa = false
asyncCompute = true

[publish]
platformName = "Windows"
productName  = "TestingProject"
buildScripts = true
cleanOutput  = true
openAfter    = true
syncEditorPak = true
usePackageTemplate = true
verifyOutput = true
outputRoot   = "D:\\AetherCore\\projects\\TestingProject\\Builds"
