# AetherCore sprite atlas

[atlas]
filter = "nearest"
import_preset = "grid"
import_provenance = "native"
pixels_per_unit = 16.00
schema_version = 2.00
sprite_count = 4.00
texture = "project://assets/textures/slime/walk32x32.png"
texture_height = 32.00
texture_width = 128.00
wrap = "clamp"

[slice]
alpha_threshold = 1.00
cell_height = 32.00
cell_width = 32.00
columns = 0.00
origin = "top-left"
padding_x = 0.00
padding_y = 0.00
rows = 0.00
spacing_x = 0.00
spacing_y = 0.00
trim_alpha = false

[sprite]
0.border_bottom = 0.00
0.border_left = 0.00
0.border_right = 0.00
0.border_top = 0.00
0.collision_count = 0.00
0.height = 32.00
0.id = "fafec320ce56b256"
0.name = "Sprite_0_0"
0.persistent_key = "grid:0:0"
0.pivot_x = 0.50
0.pivot_y = 0.50
0.width = 32.00
0.x = 0.00
0.y = 0.00
1.border_bottom = 0.00
1.border_left = 0.00
1.border_right = 0.00
1.border_top = 0.00
1.collision_count = 0.00
1.height = 32.00
1.id = "fafec420ce56b409"
1.name = "Sprite_0_1"
1.persistent_key = "grid:0:1"
1.pivot_x = 0.50
1.pivot_y = 0.50
1.width = 32.00
1.x = 32.00
1.y = 0.00
2.border_bottom = 0.00
2.border_left = 0.00
2.border_right = 0.00
2.border_top = 0.00
2.collision_count = 0.00
2.height = 32.00
2.id = "fafec120ce56aef0"
2.name = "Sprite_0_2"
2.persistent_key = "grid:0:2"
2.pivot_x = 0.50
2.pivot_y = 0.50
2.width = 32.00
2.x = 64.00
2.y = 0.00
3.border_bottom = 0.00
3.border_left = 0.00
3.border_right = 0.00
3.border_top = 0.00
3.collision_count = 0.00
3.height = 32.00
3.id = "fafec220ce56b0a3"
3.name = "Sprite_0_3"
3.persistent_key = "grid:0:3"
3.pivot_x = 0.50
3.pivot_y = 0.50
3.width = 32.00
3.x = 96.00
3.y = 0.00
