# AetherCore sprite animation

[animation]
atlas = "project://assets/textures/tex_Coin.spriteatlas.toml"
event_count = 0.00
frame_count = 4.00
loop_mode = "loop"
name = "coin_spin"
schema_version = 1.00

[frame]
0.duration = 0.12
0.sprite_id = "49e98d4d25cfaf9b"
1.duration = 0.12
1.sprite_id = "49e98c4d25cfade8"
2.duration = 0.12
2.sprite_id = "49e98f4d25cfb301"
3.duration = 0.12
3.sprite_id = "49e98e4d25cfb14e"
