# AetherCore sprite animation

[animation]
atlas = "project://assets/textures/tex_Enemy.spriteatlas.toml"
event_count = 0.00
frame_count = 1.00
loop_mode = "hold"
name = "enemy_squash"
schema_version = 1.00

[frame]
0.duration = 0.50
0.sprite_id = "0c8c8d4020bb0c17"
