# AetherCore TOML material preset

[material]
baseColorFactor = [1.0, 1.0, 1.0, 1.0]
metallicFactor = 0.0
roughnessFactor = 0.9
occlusionStrength = 1.0
emissiveFactor = [0.0, 0.0, 0.0]
alphaCutoff = 0.5
doubleSided = false
alphaBlend = false
alphaMask = false

[textures]
albedo = "project://assets/textures/tex_DebugUVTiles.png"
# normal = "project://assets/textures/your_normal.png"
# metallicRoughness = "project://assets/textures/your_metalrough.png"
# occlusion = "project://assets/textures/your_ao.png"
# emissive = "project://assets/textures/your_emissive.png"
