#pragma once

#define ICON_FA_CUBE "\xef\x86\xb2"
#define ICON_FA_PERSON_RUNNING "\xef\x9c\x8c"
#define ICON_FA_WEIGHT_HANGING "\xef\x97\x8d"
#define ICON_FA_WAND_MAGIC_SPARKLES "\xee\x8b\x8a"
#define ICON_FA_CIRCLE "\xef\x84\x91"
#define ICON_FA_VIDEO "\xef\x80\xbd"
#define ICON_FA_CIRCLE_INFO "\xef\x81\x9a"
#define ICON_FA_HASHTAG "\xef\x8a\x92"

#define ICON_FA_MAGNIFYING_GLASS "\xef\x80\x82"
#define ICON_FA_PLUS "\xef\x81\xa7"
#define ICON_FA_TRASH "\xef\x87\xb8"
#define ICON_FA_PEN "\xef\x8c\x84"
#define ICON_FA_XMARK "\xef\x80\x8d"
#define ICON_FA_FILTER "\xef\x82\xb0"
#define ICON_FA_FLOPPY_DISK "\xef\x83\x87"
#define ICON_FA_FOLDER_OPEN "\xef\x81\xbc"
#define ICON_FA_PLAY "\xef\x81\x8b"
#define ICON_FA_STOP "\xef\x81\x8d"
#define ICON_FA_ROCKET "\xef\x84\xb5"
#define ICON_FA_STAR "\xef\x80\x85"

#define ICON_FA_UP_DOWN_LEFT_RIGHT "\xef\x82\xb2"
#define ICON_FA_PALETTE "\xef\x94\xbf"
#define ICON_FA_FILM "\xef\x80\x88"
#define ICON_FA_SITEMAP "\xef\x83\xa8"
#define ICON_FA_TAG "\xef\x80\xab"
#define ICON_FA_BOLT "\xef\x83\xa7"
#define ICON_FA_GEARS "\xef\x82\x85"
#define ICON_FA_GEAR "\xef\x80\x93"
#define ICON_FA_IMAGE "\xef\x80\xbe"
#define ICON_FA_LINK "\xef\x83\x81"
#define ICON_FA_EYE "\xef\x81\xae"
#define ICON_FA_ROTATE "\xef\x8b\xb1"
#define ICON_FA_ROTATE_LEFT "\xef\x8b\xaa"
#define ICON_FA_ROTATE_RIGHT "\xef\x8b\xb9"
#define ICON_FA_EXPAND "\xef\x81\xa5"
#define ICON_FA_DIAGRAM_PROJECT "\xef\x95\x82"

#define ICON_FA_WAVE_SQUARE "\xef\xa0\xbe"
#define ICON_FA_CIRCLE_NOTCH "\xef\x87\x8e"
#define ICON_FA_HEART_PULSE "\xef\x88\x9e"
#define ICON_FA_GHOST "\xef\x9b\xa2"
#define ICON_FA_LIGHTBULB "\xef\x83\xab"
#define ICON_FA_BOX_OPEN "\xef\x92\x9e"
#define ICON_FA_CODE "\xef\x84\xa1"
#define ICON_FA_CLONE                   "\xef\x89\x8d"
#define ICON_FA_LOCK                    "\xef\x80\xa3"
#define ICON_FA_UNLOCK                  "\xef\x82\x9c"
#define ICON_FA_POWER_OFF               "\xef\x80\x91"

#define ICON_FA_BUG "\xef\x86\x88"
#define ICON_FA_GAUGE_HIGH "\xef\x98\xa5"
#define ICON_FA_CLOUD_SUN "\xef\x9b\x84"

#define ICON_FA_FOLDER "\xef\x81\xbb"
#define ICON_FA_FILE "\xef\x85\x9b"
#define ICON_FA_ARROW_UP_RIGHT_FROM_SQUARE "\xef\x82\x8e"
#define ICON_FA_COPY "\xef\x83\x85"
