# AetherCore tile set

[tile]
0.animation_fps = 8.00
0.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
0.collision = "full"
0.frame_count = 0.00
0.id = "ff11fc8d7f2d2637"
0.name = "Sprite_0_0"
0.property_count = 0.00
0.sprite_id = "68216803d036d6b9"
1.animation_fps = 8.00
1.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
1.collision = "full"
1.frame_count = 0.00
1.id = "76b225aa6a53fa81"
1.name = "Sprite_0_1"
1.property_count = 0.00
1.sprite_id = "68216703d036d506"
10.animation_fps = 8.00
10.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
10.collision = "full"
10.frame_count = 0.00
10.id = "cdf1c50c59b44ac9"
10.name = "Sprite_1_2"
10.property_count = 0.00
10.sprite_id = "5f18c303cafdfc2c"
11.animation_fps = 8.00
11.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
11.collision = "full"
11.frame_count = 0.00
11.id = "cb61645040b04861"
11.name = "Sprite_1_3"
11.property_count = 0.00
11.sprite_id = "5f18c403cafdfddf"
12.animation_fps = 8.00
12.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
12.collision = "full"
12.frame_count = 0.00
12.id = "405ff6ff44ee3f80"
12.name = "Sprite_1_4"
12.property_count = 0.00
12.sprite_id = "5f18c103cafdf8c6"
13.animation_fps = 8.00
13.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
13.collision = "full"
13.frame_count = 0.00
13.id = "6500725d7d70ccba"
13.name = "Sprite_1_5"
13.property_count = 0.00
13.sprite_id = "5f18c203cafdfa79"
14.animation_fps = 8.00
14.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
14.collision = "full"
14.frame_count = 0.00
14.id = "e978b43576cc4d7a"
14.name = "Sprite_1_6"
14.property_count = 0.00
14.sprite_id = "5f18bf03cafdf560"
15.animation_fps = 8.00
15.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
15.collision = "full"
15.frame_count = 0.00
15.id = "5caa4c084e4d11d0"
15.name = "Sprite_1_7"
15.property_count = 0.00
15.sprite_id = "5f18c003cafdf713"
16.animation_fps = 8.00
16.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
16.collision = "full"
16.frame_count = 0.00
16.id = "d31a65c5a4a1dbfb"
16.name = "Sprite_2_0"
16.property_count = 0.00
16.sprite_id = "7a253603da9d2ec3"
17.animation_fps = 8.00
17.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
17.collision = "full"
17.frame_count = 0.00
17.id = "fd6fec8e268ea7a7"
17.name = "Sprite_2_1"
17.property_count = 0.00
17.sprite_id = "7a253503da9d2d10"
18.animation_fps = 8.00
18.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
18.collision = "full"
18.frame_count = 0.00
18.id = "758b4cdb40e0ab9e"
18.name = "Sprite_2_2"
18.property_count = 0.00
18.sprite_id = "7a253803da9d3229"
19.animation_fps = 8.00
19.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
19.collision = "full"
19.frame_count = 0.00
19.id = "28e65bef4c5f78ac"
19.name = "Sprite_2_3"
19.property_count = 0.00
19.sprite_id = "7a253703da9d3076"
2.animation_fps = 8.00
2.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
2.collision = "full"
2.frame_count = 0.00
2.id = "93afdd08dc0cf2c1"
2.name = "Sprite_0_2"
2.property_count = 0.00
2.sprite_id = "68216603d036d353"
20.animation_fps = 8.00
20.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
20.collision = "full"
20.frame_count = 0.00
20.id = "47a0bf35cf2b3433"
20.name = "Sprite_2_4"
20.property_count = 0.00
20.sprite_id = "7a253a03da9d358f"
21.animation_fps = 8.00
21.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
21.collision = "full"
21.frame_count = 0.00
21.id = "5b67cce08e53b5a7"
21.name = "Sprite_2_5"
21.property_count = 0.00
21.sprite_id = "7a253903da9d33dc"
22.animation_fps = 8.00
22.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
22.collision = "full"
22.frame_count = 0.00
22.id = "cea1a4bddaf752d3"
22.name = "Sprite_2_6"
22.property_count = 0.00
22.sprite_id = "7a253c03da9d38f5"
23.animation_fps = 8.00
23.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
23.collision = "full"
23.frame_count = 0.00
23.id = "5304e03492c0993f"
23.name = "Sprite_2_7"
23.property_count = 0.00
23.sprite_id = "7a253b03da9d3742"
3.animation_fps = 8.00
3.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
3.collision = "full"
3.frame_count = 0.00
3.id = "2618e50328c85720"
3.name = "Sprite_0_3"
3.property_count = 0.00
3.sprite_id = "68216503d036d1a0"
4.animation_fps = 8.00
4.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
4.collision = "full"
4.frame_count = 0.00
4.id = "ab55da2d0ee0c838"
4.name = "Sprite_0_4"
4.property_count = 0.00
4.sprite_id = "68216c03d036dd85"
5.animation_fps = 8.00
5.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
5.collision = "full"
5.frame_count = 0.00
5.id = "f71daadfbb49dd2f"
5.name = "Sprite_0_5"
5.property_count = 0.00
5.sprite_id = "68216b03d036dbd2"
6.animation_fps = 8.00
6.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
6.collision = "full"
6.frame_count = 0.00
6.id = "3a574777f8e4c9d1"
6.name = "Sprite_0_6"
6.property_count = 0.00
6.sprite_id = "68216a03d036da1f"
7.animation_fps = 8.00
7.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
7.collision = "full"
7.frame_count = 0.00
7.id = "616c51daa89849bb"
7.name = "Sprite_0_7"
7.property_count = 0.00
7.sprite_id = "68216903d036d86c"
8.animation_fps = 8.00
8.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
8.collision = "full"
8.frame_count = 0.00
8.id = "eed1af32ef114b5c"
8.name = "Sprite_1_0"
8.property_count = 0.00
8.sprite_id = "5f18c503cafdff92"
9.animation_fps = 8.00
9.atlas = "project://assets/textures/tex_Tiles.spriteatlas.toml"
9.collision = "full"
9.frame_count = 0.00
9.id = "7418496d85d97c80"
9.name = "Sprite_1_1"
9.property_count = 0.00
9.sprite_id = "5f18c603cafe0145"

[tileset]
cell_size = 1.00
name = "level2"
schema_version = 1.00
tile_count = 24.00
